#pragma once

#include "psxrecomp/ir/ir.h"
#include <string>
#include <vector>

namespace psxrecomp
{
namespace recompiler
{

/**
 * @brief Options for the recompilation pipeline.
 */
struct PipelineOptions
{
    std::string outputDirectory;
    bool enableOptimizations = true;
    bool preserveSymbols = false;
    bool verbose = false;
};

/**
 * @brief Output paths generated by the pipeline.
 */
struct PipelineArtifacts
{
    std::string moduleName;
    std::string headerPath;
    std::string sourcePath;
    std::string buildPath;
};

/**
 * @brief Result of running the pipeline.
 */
struct PipelineResult
{
    bool success = false;
    PipelineArtifacts artifacts;
    std::vector<std::string> warnings;
    std::string errorMessage;
};

/**
 * @brief End-to-end static recompilation pipeline.
 */
class RecompilationPipeline
{
  public:
    explicit RecompilationPipeline(PipelineOptions options);

    /**
     * @brief Run the pipeline on the provided input.
     * @param inputPath ISO/BIN/PSX-EXE path.
     * @return Pipeline result with artifacts or error.
     */
    PipelineResult run(const std::string& inputPath);

  private:
    PipelineOptions m_options;
};

} // namespace recompiler
} // namespace psxrecomp
