#pragma once

#include "psxrecomp/ir/ir.h"
#include "psxrecomp/types.h"
#include <optional>
#include <string>
#include <vector>

namespace psxrecomp
{
namespace recompiler
{

struct PipelineDiagnosticContext
{
    std::string file;
    std::string module;
    std::optional<u32> offset;
};

struct PipelineDiagnostic
{
    std::string code;
    std::string severity;
    std::string message;
    PipelineDiagnosticContext context;
};

struct ExeCandidateInfo
{
    std::string path;
    u32 loadAddress = 0;
    u32 loadSize = 0;
    u32 entryPoint = 0;
    std::string hash;
    bool valid = false;
    std::vector<PipelineDiagnostic> diagnostics;
};

struct ExeSelectionInfo
{
    std::string rule;
    std::string reason;
    std::string selectedPath;
};

struct DiscMetadata
{
    std::string path;
    std::string volumeLabel;
    u32 discIndex = 0;
};

struct DiscSetMetadata
{
    std::string setName;
    u32 activeDiscIndex = 0;
    std::vector<DiscMetadata> discs;
};

/**
 * @brief Options for the recompilation pipeline.
 */
struct PipelineOptions
{
    std::string outputDirectory;
    bool enableOptimizations = true;
    bool preserveSymbols = false;
    bool verbose = false;
    std::vector<std::string> discPaths;
    size_t activeDiscIndex = 0;
    std::string manifestTimestamp;
    std::string pipelineVersion = "1.0.0";
};

/**
 * @brief Output paths generated by the pipeline.
 */
struct PipelineArtifacts
{
    std::string moduleName;
    std::string headerPath;
    std::string sourcePath;
    std::string buildPath;
    std::string manifestPath;
};

/**
 * @brief Result of running the pipeline.
 */
struct PipelineResult
{
    bool success = false;
    PipelineArtifacts artifacts;
    std::vector<std::string> warnings;
    std::vector<PipelineDiagnostic> diagnostics;
    std::vector<ExeCandidateInfo> exeCandidates;
    struct FunctionMetadata
    {
        std::string name;
        Address entryAddress = 0;
        Address endAddress = 0;
        bool hasPrologue = false;
        bool hasEpilogue = false;
        std::vector<Address> directCalls;
        size_t indirectCallCount = 0;
    };
    std::vector<FunctionMetadata> functions;
    ExeSelectionInfo selectionInfo;
    DiscSetMetadata discSet;
    std::string errorMessage;
};

/**
 * @brief End-to-end static recompilation pipeline.
 */
class RecompilationPipeline
{
  public:
    explicit RecompilationPipeline(PipelineOptions options);

    /**
     * @brief Run the pipeline on the provided input.
     * @param inputPath ISO/BIN/PSX-EXE path.
     * @return Pipeline result with artifacts or error.
     */
    PipelineResult run(const std::string& inputPath);

  private:
    PipelineOptions m_options;
};

} // namespace recompiler
} // namespace psxrecomp
